# Generated by Django 5.0.14 on 2025-07-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test1',
            new_name='tests',
        ),
    ]
