# Generated by Django 5.0.14 on 2025-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
